# Generated by Django 4.2.5 on 2023-11-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('tname', models.CharField(max_length=100)),
                ('tdesc', models.CharField(max_length=500)),
                ('euser', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
    ]
